### ISSUE TITLE
Doesn't work on Gist

### ISSUE THREAD

**Issue by brandonb927** [tmlee/wider_github#2]
I love this idea, its been a thorn in my side since I started using Github that I couldn't easily expand the code viewer. Another useful area for this extension would be for Gist. Currently It doesn't work as expected, but I'm sure its not built in yet :)

**Comment by tmlee** [comment]
Hi @brandonb927, thanks for the feedback. That's certainly a good addition, i'll be interested to get that in.

**Comment by tmlee** [comment]
You can give it a try, now that i have pushed an update :)
